"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const createBlog_routes_1 = __importDefault(require("../createBlog/routes/createBlog.routes"));
const getBlog_routes_1 = __importDefault(require("../getBlog/routes/getBlog.routes"));
const updateBlog_routes_1 = __importDefault(require("../updateBlog/routes/updateBlog.routes"));
const deleteBlog_routes_1 = __importDefault(require("../deleteBlog/routes/deleteBlog.routes"));
const search_route_1 = __importDefault(require("../searchBlog/routes/search.route"));
const blogReactions_route_1 = __importDefault(require("../reactions/routes/blogReactions.route"));
const BlogRouter = express_1.default.Router();
BlogRouter.use(createBlog_routes_1.default);
BlogRouter.use(getBlog_routes_1.default);
BlogRouter.use(updateBlog_routes_1.default);
BlogRouter.use(deleteBlog_routes_1.default);
BlogRouter.use(search_route_1.default);
BlogRouter.use(blogReactions_route_1.default);
exports.default = BlogRouter;
